name: Build project and run ctest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    name: Build with ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: "GCC 14"
            container: gcc:14
          - name: "GCC 15"
            container: gcc:15
          - name: "Clang 20"
            container: silkeh/clang:20

    container:
      image: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y cmake curl doxygen git libtool unzip pkg-config tar zip

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        doNotCache: false

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $(nproc) --verbose

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build --build-config ${{env.BUILD_TYPE}} --verbose
